### ISSUE TITLE
Installing GLPK on a Mac 

### ISSUE THREAD

**Issue by EmiFej** [OSeMOSYS/OSeMOSYS#102]
**Describe the problem**
When following the installation guide on how to install GLPK on Mac during a course in 2019, many students with Mac computers faced some issues when running or trying to install GLPK on their Mac computers. In order to minimize these problems this year, the following installation guide was created.  
**Expected content**
Following the installation guide below should make it possible for Mac owners to run .txt files and thus use GLPK and OSeMOSYS. 
**Proposed change**
1. Open the terminal
2. Enter the following: xcode-select --install
3. After the command line developer tools are installed, go to:
https://brew.sh
4. On the home page, copy the ”Install Homebrew” link to the Terminal prompt on your Mac. 
5. Follow the instructions in the Terminal prompt, it will require your computer password.
6. After the installation of HomeBrew is completed, you should see this line in the Terminal prompt: ”==> Installation successful!”.
7. Check that HomeBrew is correctly installed by entering ”brew help” in the TerminalPrompt. This should give you examples for usage or troubleshooting.
8. Enter the following command into the Terminal prompt: brew install glpk

From step 8 you can jump straight into step 13.

> 9. In Finder, open the GO menu and click on Go to Folder. Type: /usr/local/Cellar
> 10. In the folder glpk/4.65/bin you will find the glpsol program. Create a folder called OSEMOSYS on your Desktop and copy the glpsol program into it.
> 11. Download the model and data .txt files provided on the OSeMOSYS website, under Get Started. Copy the .txt files into the same OSEMOSYS folder where you copy pasted the glpsol. 
> 12. To run the model go back to the Terminal, locate the OSEMOSYS file in the desktop by typing:cd desktop/OSEMOSYS

13. And to run the model type the following line and press Enter: glpsol -m OSEMOSYS_2011_11_08.txt -d UTOPIA_2011_11_08.txt -o Results.txt

**Comment by willu47** [comment]
Hi @EmiFej - many thanks for this.  We should definitely add better instructions for Mac users.

I have a question about the process you've documented above.  Is step 9 through 12 necessary?  Once you've installed glpk through brew, the `glpsol` command should be available in the terminal.

**Comment by EmiFej** [comment]
Hi @willu47 , I don't think it is necessary in order to run the program, but I'm guessing it's easier to have the glpsol file on the desktop in order to find the cd in the Terminal prompt easier. (cd desktop/OSEMOSYS vs cd /usr/local/Cellar glpk/4.65/bin), and the .txt files that you want to run have to be saved in the same folder I believe, which makes it easier to put them in to the desktop folder OSEMOSYS. 
What do you think?

**Comment by willu47** [comment]
Once GLPK is installed, you should be able to run the command `glpsol` from any terminal without referencing the program directly. In otherwords, brew installs the command `glpsol` so that it is available from any location.

**Comment by EmiFej** [comment]
Thank you for the information. Is it a requirement to have the .txt files that you want to run in the same folder as the glpsol?

**Comment by willu47** [comment]
No. You only need to pass the relative path (to the folder in which you are in) to the glpsol command.

For example if the folder you are in contains `osemosys.txt` and `data.txt`, then the command would be `glpsol -m osemosys.txt -d data.txt`

**Comment by EmiFej** [comment]
Thank you for the clarification. In that case steps 9-12 are unnecessary.

**Comment by willu47** [comment]
Great, @EmiFej - would you like to make this addition to the documentation and submit a pull request?  You can reference this issue using #102 in the pull request text.

**Comment by EmiFej** [comment]
Dear @willu47 , I would gladly help out regarding this matter, but I'm not sure on how to make the addition and create a pull request. I followed the "Creating the pull request" guide, however I do not see the branch that contain my commit. If you could explain the procedure this time I might be able to fix the issue and be better prepared next time when something similar comes up.

**Comment by Bahramkhan15** [comment]
very helpful thank you

**Comment by FraGard** [comment]
Thanks @EmiFej and @willu47 , it's working well. A note to Step 8 ('brew install glpk'): before running the command, make sure you allow cookies in your default browser. The command will try to connect to some urls that could otherwise be blocked.
