### ISSUE TITLE
Solves, but seemingly incorrectly. How to debug?

### ISSUE THREAD

**Issue by Irshaadv** [OSeMOSYS/OSeMOSYS#14]
Hello there, 

FIrstly, I am unsure if this is the best place to post this: the Reddit thread seems closed, and there seems to be no forum / Google Group? (unless I missed it). So please forgive me if this is not the correct place. 

Second: thank you to everyone that has been involved in makign OSeMOSYS happen - I deeply appreciate it. 

Third, my problem is as follows:

- I've managed to get the .py script running succesfully with glpk as the solver. 
- It runs the UTOPIA case study using the .dat file found in this repo. 
- It states that it has solved succesfully, when I think it has not. Specifically, the objective function value I get is "29446.861..." when I think I should be getting something in the order of ~$36billion?

So the question is, how do I debug this? Has anyone had similiar problems? Is there an error perhaps in the .dat file? Or the .py model? I haven't altered either, so I wonder if perhaps there is an error in how I've run the model on my PC?

I would really appreciate any help on this. 

Thanks!
Irshaad

**(EDIT: Just found the Google Group - moving this there!. So Sorry)**

**Comment by HauHe** [comment]
No problem! Happy you found the forum :)
