### ISSUE TITLE
Ensure clear link to the OpTIMUS Community from OSeMOSYS github organisation

### ISSUE THREAD

**Issue by willu47** [OSeMOSYS/OSeMOSYS#44]

**Comment by AgnesBelt** [comment]
Hi @willu47,
I could add some description with link to OpTIMUS. However at the moment I don't think I have the rights for that. I will send you something separately.

**Comment by AgnesBelt** [comment]
I added the related OpTIMUS link in the README file of the OSeMOSYS/OSeMOSYS repository. I think this issue can be closed.
