### ISSUE TITLE
Set up a Google form for people to add their news info + banner on the newsletter to ask for people to report relevant news and also ask on the Forum prior to the Monthly newsletter

### ISSUE THREAD

**Issue by willu47** [OSeMOSYS/OSeMOSYS#45]

**Comment by AgnesBelt** [comment]
Hi Will,
Here a draft of the requested Google form: https://docs.google.com/forms/d/155mbiy5OhzbyWnOxOTGVS8s_-fScqAVUJZ-FWMDSCnQ/edit?usp=sharing
Please feel free to provide me feedback or directly edit the form.
Best, Agnese

**Comment by willu47** [comment]
Looks good @AgnesBelt
