### ISSUE TITLE
Add section in newsletter on how to contribute content

### ISSUE THREAD

**Issue by willu47** [OSeMOSYS/OSeMOSYS#46]

**Comment by AgnesBelt** [comment]
Hi Will, 
Since the newsletter is about to be ready for this month, should I add a banner with link to the new OSeMOSYS repository and the contributing.md file? Or should I just link the repository for now to the news you wrote?

**Comment by willu47** [comment]
Hi @AgnesBelt - this should be a section in the newsletter on how to contribute news to the newsletter, not the OSeMOSYS code!

**Comment by AgnesBelt** [comment]
Hi @willu47, 
Indeed. Sorry for the misunderstanding. I was actually preparing already the correct google form. 
I have added it now, waiting for any comment or feedback if needed.

**Comment by willu47** [comment]
Looks good @AgnesBelt
