### ISSUE TITLE
B.4 Update links to OSeMOSYS repository on website, in forum and elsewhere

### ISSUE THREAD

**Issue by willu47** [OSeMOSYS/OSeMOSYS#52]

**Comment by AgnesBelt** [comment]
In progress:
- [x] website
- [x] forum
- [x] newsletter

**Comment by willu47** [comment]
@AgnesBelt - if you're finished with this, could you close the issue?

**Comment by AgnesBelt** [comment]
I am adding permanent links to the Manual and to the Newsletter. I will close the issue once done with it (probably by today).

**Comment by AgnesBelt** [comment]
Finished!
