### ISSUE TITLE
Review the most appropriate license for OSeMOSYS?

### ISSUE THREAD

**Issue by willu47** [OSeMOSYS/OSeMOSYS#87]
If not Apache 2.0, can we change to the recommended license?

**Comment by abhishek0208** [comment]
The [openmod wiki has a page](https://wiki.openmod-initiative.org/wiki/Choosing_a_license) dedicated to discussing this. 

The following text is relevant to choosing a license for OSeMOSYS:
"Are you ok with your code becoming part of a closed-source commercial software product?
* No: GPL
* Yes: permissive licenses (MIT/BSD/Apache)

Do you want to force users to publish their improvements to your software, or to software they develop based on your software, under the same licence?
*No: permissive licenses (MIT/BSD/Apache). This makes the code more broadly usable, but also allows people to take the code without sharing their improvements.
*Yes: GPL. This ensures that any future changes and improvements to the code remain free and open"

There's more information, including a comparison of license options, here: https://choosealicense.com/

Based on the above, I would propose either **staying with the current Apache license** or **switching to an MIT license**. The only addition in the former is that it *explicitly grants patent rights*.

**Comment by willu47** [comment]
Thanks for looking into this @abhishek0208. It looks like the Apache license is fine for our current needs. The one issue I spotted with Apache is that it requires derivative works (e.g. any re-implementation of the GNU MathProg OSeMOSYS) to be named differently. So OSeMOSYS_GAMS and OSeMOSYS_Pyomo aren't sufficiently different from OSeMOSYS to satisfy this. If we're happy with the close naming (and I believe we are), then the MIT license which has no such provision may be a better fit.

**Comment by tniet** [comment]
Thanks for looking into those details @abhishek0208 and @willu47 - What is involved in changing licenses?  Would that be for future versions or is the Apache license compatible with the MIT license?  It would be nice to keep the naming the way we have it and allow derivatives to have derivative names.

**Comment by willu47** [comment]
I believe that we can change licenses for all future releases of the code, but that previous versions will still be under the Apache license.

**Comment by willu47** [comment]
We've decided to stick with the Apache-2.0 license.
