### ISSUE TITLE
Develop script to enforce naming conventions

### ISSUE THREAD

**Issue by willu47** [OSeMOSYS/OSeMOSYS#95]
Adopting a naming standard for processes in OSeMOSYS greatly eases pre-processing and post-processing of data and results.

A script which checks the naming of technologies and processes against a template or set of recommended formats would help enforce the adoption of naming processes.

**Comment by tniet** [comment]
I'm not sure enforce is quite the right word, as we can't force others to follow a naming convention we decide upon.  That being said, providing a naming convention guideline and being more generous with technical support for those who follow it is a good idea.  And it would make support debugging easier.

**Comment by willu47** [comment]
Yes, I meant "enforce" for those who want it!  Perhaps "validation" would be a better term.  Anyhow, a script which you can run to check your data file and warns you of any potential issues would be invaluable and a good precaution against some nefarious bugs.

**Comment by willu47** [comment]
This is being looked at in [otoole](http://github.com/osemosys/otoole), so closing here.
