### ISSUE TITLE
[DOCS] Guidance for OSeMOSYS extensions outdated

### ISSUE THREAD

**Issue by willu47** [OSeMOSYS/OSeMOSYS#97]
**Describe the problem**

The [documentation](https://osemosys.readthedocs.io/en/latest/manual/Advanced%20functionalities.html#modifications-enhancements-and-extensions-of-the-main-code) on submission of extensions does not reflect the latest thoughts on the proces.

**Expected content**

It should match that in the [OEP issue template](https://github.com/OSeMOSYS/OSeMOSYS/blob/master/.github/ISSUE_TEMPLATE/osemosys-enhancement-proposal.md)

Some of the following should also be added:

> The situation is complicated somewhat by there being multiple different implementations of OSeMOSYS, in GNU MathProg, GAMS, Pyomo and Pulp.  These separate implementations are coordinated in the main OSeMOSYS repository.
> 
> For small additions, like tweaks to the documentation, or minor fixes to each of the implementations, contributions should be directed to the repositories of the individual repositories, using Github issues and pull requests there.
> 
> For major additions to the formulation of OSeMOSYS, there is a separate process (currently under development) - which includes submission of an OSeMOSYS Enhancement Proposal (OEP) using the Github Issue tracker on the main OSeMOSYS repository.  This should contain information such as that included in your e-mail, as well as a more detailed description of the proposed changes. This process will replace that described in the documentation. OEPs can then be discussed with the administrators of the OSeMOSYS organisation, and representatives of the OSeMOSYS Steering Committee and will then be either approved, rejected, or changes requested e.g. like a peer-review.
> 
> If an OEP is accepted, then the developers can submit a pull request in the repository of their chosen implementation linking back to the original OEP and it will be reviewed by the admins.  The submission will also require additions to the main documentation.

**Proposed change**

- [x] Update the documentation to match the OEP issue template.
- [ ] Also update the `Contributing.md` in the main repository

**Comment by AgnesBelt** [comment]
Dear @willu47, I have created a new section and added the info concerning OEP on the OSeMOSYS manual. Please, let me know if that is fine by you. Thanks!
